config/routes.rb
EliteHouse::Application.routes.draw do
 scope '(:locale)', :locale => /lv|ru/ do
   resources :categories, :only => [ :index ] do
     get 'contacts', :on => :collection
     get 'building', :on => :collection
     get 'sitemap',  :on => :collection
     resources :sub_categories, :only => [ :index ]
   end
   
   resources :sub_categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   resources :categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   namespace :admin do
     resources :categories, :sub_categories, :furniture#, :only => [ :new, :update, :destroy, :edit, :create ]
     match '/' => "base#admin_actions"
   end
   
   match '/sitemap(.:format)' => 'categories#sitemap'
   match '/:locale' => 'categories#index'
   match '/', :to => redirect('/lv/categories')
   root :to => 'categories#index'
 end
end

app/models/sub_category.rb
class SubCategory < ActiveRecord::Base
  has_many :furniture, :dependent => :destroy
  belongs_to :category
  after_initialize :set_pritority
  validates_presence_of :category
  has_attached_file :image, 
                    :styles => { :medium => "300x300>",
                                 :thumb => "100x100>" }
  
  
  def name
    read_attribute( I18n.locale == :lv ? :name : :name_ru ) 
  end
  
  def description
    read_attribute( I18n.locale == :lv ? :description : :description_ru ) 
  end
  
  def key
    self.id
  end
  
  private
  
  def set_pritority
    self.priority = SubCategory.count unless priority
  end
  
end

app/controllers/admin/sub_categories_controller.rb
class Admin::SubCategoriesController < Admin::BaseController
  before_filter :load_sub_category , :only => [:edit, :update, :destroy]
  
  def index
    @sub_categories = SubCategory.find(:all, :order => "priority DESC")
  end
  
  def new
    @sub_category = SubCategory.new
  end
  
  def edit
    render :new
  end
  
  def create
    @sub_category = SubCategory.new(params[:sub_category])
    
    if @sub_category.save
      redirect_to admin_sub_categories_path
    else
      render :new
    end
  end
  
  def update
    if @sub_category.update_attributes(params[:sub_category])
      redirect_to admin_sub_categories_path
    else
      render :new
    end
  end
  
  def destroy
    @sub_category.destroy
    redirect_to admin_sub_categories_path
  end
  
  private
  
  def load_sub_category
    @sub_category = SubCategory.find(params[:id])
  end
end

app/controllers/sub_categories_controller.rb
class SubCategoriesController < ApplicationController
end

app/helpers/admin/sub_categories_helper.rb
module Admin::SubCategoriesHelper
end

app/helpers/sub_categories_helper.rb
module SubCategoriesHelper
end

app/views/admin/sub_categories/index.erb
<% unless @sub_categories.empty? %>
  <table class="admin_table" id="category_list_admin">
    <tr>
      <th>Sub Category Name</th>
      <th>Sub Category Priority</th>
      <th>Category</th>
      <th>&nbsp;</th>
    </tr>
    
    <%  @sub_categories.each do |c| %>
      <tr>
        <td>
          <a class="admin" href="<%= edit_admin_sub_category_path(:id => c) %>"><%= c.name %></a>
        </td>
        <td>
          <%= c.priority %>
        </td>
        <td>
          <%= c.category.name %>
        </td>
        <td>
          <%= link_to "Delete", { :controller => "admin/sub_categories", :action => "destroy", :id => c.id }, :class => "admin", :method => :delete, :confirm => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p class="empty_list"> No sub categories added yet.</p>
<% end %>
  <a class="admin" href="<%= new_admin_sub_category_path %>"> Add new sub_category </a>

app/views/admin/sub_categories/new.erb
<%= simple_form_for [:admin, @sub_category], :html => { :multipart => true } do |f| %>
	<%=	f.input :name %>
	<%=	f.input :name_ru %>
	<%=	f.input :description, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :description_ru, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :priority %>
	<%= f.association :category, :collection => Category.all(:order => 'name')%>
	<%=	f.button :submit, :value => "Saglabāt" %>
<% end %>