config/routes.rb
EliteHouse::Application.routes.draw do
 scope '(:locale)', :locale => /lv|ru/ do
   resources :categories, :only => [ :index ] do
     get 'contacts', :on => :collection
     get 'building', :on => :collection
     get 'sitemap',  :on => :collection
     resources :sub_categories, :only => [ :index ]
   end
   
   resources :sub_categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   resources :categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   namespace :admin do
     resources :categories, :sub_categories, :furniture#, :only => [ :new, :update, :destroy, :edit, :create ]
     match '/' => "base#admin_actions"
   end
   
   match '/sitemap(.:format)' => 'categories#sitemap'
   match '/:locale' => 'categories#index'
   match '/', :to => redirect('/lv/categories')
   root :to => 'categories#index'
 end
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  layout 'admin/application'
  before_filter :authenticate_admin
  
  def admin_actions
    render "admin_actions"
  end
  
  private
  def authenticate_admin
    if RAILS_ENV == "production"
      authenticate_or_request_with_http_basic do |username, password|
        username == USERS.keys.first && password == USERS[username]
      end
    end
  end
end

app/views/admin/base/admin_actions.erb
<ul id="admin_actions_list">
  <li> <a class="admin" href="<%= admin_categories_path %>">Categories list</a> </li>
  <li> <a class="admin" href="<%= admin_sub_categories_path %>">Sub Categories list</a> </li>
  <li> <a class="admin" href="<%= admin_furniture_index_path %>">Furniture list</a> </li>
  <li> <a class="admin" href="#">Image gallery configuration</a> </li>
</ul>