config/routes.rb
EliteHouse::Application.routes.draw do
 scope '(:locale)', :locale => /lv|ru/ do
   resources :categories, :only => [ :index ] do
     get 'contacts', :on => :collection
     get 'building', :on => :collection
     get 'sitemap',  :on => :collection
     resources :sub_categories, :only => [ :index ]
   end
   
   resources :sub_categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   resources :categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   namespace :admin do
     resources :categories, :sub_categories, :furniture#, :only => [ :new, :update, :destroy, :edit, :create ]
     match '/' => "base#admin_actions"
   end
   
   match '/sitemap(.:format)' => 'categories#sitemap'
   match '/:locale' => 'categories#index'
   match '/', :to => redirect('/lv/categories')
   root :to => 'categories#index'
 end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, :dependent => :destroy
  has_many :furniture, :dependent => :destroy
  after_initialize :set_defaults
  
  scope :active, where( "active = 't'" )
  
  def name
    read_attribute( I18n.locale == :lv ? :name : :name_ru ) 
  end
  
  def description
    read_attribute( I18n.locale == :lv ? :description : :description_ru ) 
  end
  
  def special?
    special
  end
  
  def dining_room?
    read_attribute(:name).match /Ēdamistaba/
  end
  
  def guest_room?
    read_attribute(:name).match /Viesistaba/
  end
  
  private
  
  def set_defaults
    self.priority = Category.count if priority.nil?
    self.active   = true if active.nil?
    self.special  = false if id.nil? && special.nil?
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  before_filter :load_category , :only => [:edit, :update, :destroy]
  
  def index
    @categories = Category.find(:all, :order => "priority DESC")
  end
  
  def new
    @category = Category.new
  end
  
  def edit
    render :new
  end
  
  def create
    if Category.create(params[:category])
      redirect_to admin_categories_path
    else
      render :new
    end
  end
  
  def update
    if @category.update_attributes(params[:category])
      redirect_to admin_categories_path
    else
      render :new
    end
  end
  
  def destroy
    @category.destroy
    redirect_to admin_categories_path
  end
  
  private
  
  def load_category
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
  end
  
  def contacts
    render :template => ( I18n.locale == :lv ? "categories/contacts" : "categories/contacts_ru" ) 
  end
  
  def sitemap
    @categories = Category.all
    @sub_categories = SubCategory.all
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.erb
<% unless @categories.empty? %>
  <table class="admin_table" id="sub_category_list_admin">
    <tr>
      <th>Category Name</th>
      <th>Category Priority</th>
      <th>&nbsp;</th>
    </tr>
    
    <%  @categories.each do |c| %>
      <tr>
        <td>
          <a class="admin "href="<%= edit_admin_category_path(:id => c) %>"><%= c.name %></a>
        </td>
        <td>
          <%= c.priority %>
        </td>
        <td>
          <%= link_to "Delete", { :controller => "admin/categories", :action => "destroy", :id => c.id }, :class => "admin", :method => :delete, :confirm => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p class="empty_list"> No categories added yet.</p>
<% end %>
  <a class="admin" href="<%= new_admin_category_path %>"> Add new category </a>

app/views/admin/categories/new.erb
<%= simple_form_for [:admin, @category] do |f| %>
	<%=	f.input :name %>
	<%=	f.input :name_ru %>
	<%=	f.input :description, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :description_ru, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :priority %>
	<%=	f.input :active %>
	<%=	f.input :special %>
	<%=	f.button :submit, :value => "Saglabāt" %>
<% end %>