config/routes.rb
EliteHouse::Application.routes.draw do
 scope '(:locale)', :locale => /lv|ru/ do
   resources :categories, :only => [ :index ] do
     get 'contacts', :on => :collection
     get 'building', :on => :collection
     get 'sitemap',  :on => :collection
     resources :sub_categories, :only => [ :index ]
   end
   
   resources :sub_categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   resources :categories, :only => [ :index ] do
     resources :furniture, :only => [ :index, :show ]
   end
   
   namespace :admin do
     resources :categories, :sub_categories, :furniture#, :only => [ :new, :update, :destroy, :edit, :create ]
     match '/' => "base#admin_actions"
   end
   
   match '/sitemap(.:format)' => 'categories#sitemap'
   match '/:locale' => 'categories#index'
   match '/', :to => redirect('/lv/categories')
   root :to => 'categories#index'
 end
end

app/models/furniture.rb
class Furniture < ActiveRecord::Base
  belongs_to :category
  belongs_to :sub_category
  validates_presence_of :category
  #validates_presence_of :sub_category, :if => lambda { |f| self.category.sub_categories.size > 0 }
  after_initialize :set_priority
  has_many :images, :dependent => :destroy
  accepts_nested_attributes_for :images, :reject_if => lambda { |t| t['picture'].nil? && t['id'].nil? }, :allow_destroy => true  
  
  def name
   read_attribute( I18n.locale == :lv ? :name : :name_ru ) 
  end
  
  def description
    read_attribute( I18n.locale == :lv ? :description_lv : :description_ru ) 
  end
  
  def self.find_for_index(params)
    if params[:sub_category_id]
      self.where(:sub_category_id => params[:sub_category_id])
    else
      self.where(:category_id => params[:category_id])
    end
  end
  
  def main_image
    images.main.first || images.first
  end
  
  private
  
  def set_priority
    self.priority = Furniture.count unless priority
  end
end

app/controllers/admin/furniture_controller.rb
class Admin::FurnitureController < Admin::BaseController
  before_filter :load_furniture , :only => [:edit, :update, :destroy]

  def index
    @furniture = Furniture.find(:all, :order => "priority DESC")
  end

  def new
    @furniture = Furniture.new
    10.times { @furniture.images.build }
  end

  def edit
    number = 10 - @furniture.images.size
    number.times { @furniture.images.build }
    render :new
  end

  def create
    @furniture = Furniture.new(params[:furniture])

    if @furniture.save
      redirect_to admin_furniture_index_path
    else
      render :new
    end
  end

  def update
    if @furniture.update_attributes(params[:furniture])
      redirect_to admin_furniture_index_path
    else
      render :new
    end
  end
  
  def destroy
    @furniture.destroy
    redirect_to admin_furniture_index_path
  end

  private

  def load_furniture
    @furniture = Furniture.find(params[:id])
  end
end

app/controllers/furniture_controller.rb
class FurnitureController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]
  
  def index
    @furniture = Furniture.find_for_index(params)
    @category = Category.find(params[:category_id])  if params[:category_id]
    @sub_category = SubCategory.find(params[:sub_category_id]) if params[:sub_category_id]
  end
  
  def show
    @furniture = Furniture.find(params[:id])
    render :layout => false
  end
end

app/helpers/admin/furniture_helper.rb
module Admin::FurnitureHelper
end

app/helpers/furniture_helper.rb
module FurnitureHelper
end

app/views/admin/furniture/index.erb
<% unless @furniture.empty? %>
  <table class="admin_table" id="category_list_admin">
    <tr>
      <th>Furniture Name</th>
      <th>Sub Category Priority</th>
      <th>Category</th>
      <th>Sub Category</th>
      <th>Image</th>
      <th>&nbsp;</th>
    </tr>
    
    <%  @furniture.each do |c| %>
      <tr>
        <td>
          <a class="admin" href="<%= edit_admin_furniture_path(:id => c) %>"><%= c.name %></a>
        </td>
        <td>
          <%= c.priority %>
        </td>
        <td>
          <%= c.category.name %>
        </td>
				<td>
          <%= c.sub_category.name if c.sub_category %>
        </td>
        <td>
          <%= image_tag c.main_image.url(:thumb) unless c.images.empty? %>
        </td>
        <td>
          <%= link_to "Delete", { :controller => "admin/furniture", :action => "destroy", :id => c.id }, :class => "admin", :method => :delete, :confirm => "Are you sure?" %>
        </td>
      </tr>
    <% end %>
  </table>
<% else %>
  <p class="empty_list"> No sub categories added yet.</p>
<% end %>
  <a class="admin" href="<%= new_admin_furniture_path %>"> Add new furniture </a>

app/views/admin/furniture/new.erb
<%= simple_form_for [:admin, @furniture], :url => furniture_form_url, :html => { :multipart => true } do |f| %>
	<%=	f.input :name %>
	<%=	f.input :name_ru %>
	<%=	f.input :description_lv, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :description_ru, :as => :text, :input_html => {:columns => 6, :rows => 4} %>
	<%=	f.input :priority %>
	<%= f.association :category, :collection => Category.all(:order => 'name')%>
	<%= f.association :sub_category, :collection => SubCategory.all(:order => 'name')%>
	
	<%= f.simple_fields_for :images do |builder| %>
	    <% unless builder.object.id.nil? %>
	      <div id="image_container_<%= builder.object.id %>">
          <%= image_tag builder.object.url(:medium) %>
          <%= builder.hidden_field :_destroy %>  
          <%= link_to "remove", "javascript:remove_fields(#{builder.object.id})", :class => "admin", :id => builder.object.id %>
        </div>
      <% else %>
        <%= builder.file_field :picture %>
      <% end %>
      
      <%= builder.input :main %>
      <%= builder.input :gallery_flag %>
  <% end %>
  
	<%=	f.button :submit, :value => "Saglabāt" %>
<% end %>